# Generated by Django 4.2.27 on 2025-12-24 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_jebii'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_ser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('course', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='jebii',
        ),
    ]
